### ISSUE TITLE
400 Bad Request - Request must contain an kbn-xsrf header

### ISSUE THREAD

**Issue by justinmchase** [mikael-lindstrom/amazon-elasticsearch-proxy#2]
This used to work for me but when I went to try it again today it seems to be having an issue.

Its calling out to this url after partially loading the page:
```
http://127.0.0.1:9200/_plugin/kibana/es_admin/.kibana/index-pattern/_search?stored_fields=
```

It gets a 400 error and then fails to load kibana.

<img width="498" alt="screenshot 2017-11-30 15 35 42" src="https://user-images.githubusercontent.com/10974/33456161-292e7986-d5e4-11e7-8d27-11cffff7e057.png">

Here is the error details:

<img width="430" alt="screenshot 2017-11-30 15 37 33" src="https://user-images.githubusercontent.com/10974/33456247-6ea8dd3a-d5e4-11e7-8bf7-888449826909.png">

**Comment by mikael-lindstrom** [comment]
I was able to reproduce the problem using Elasticsearch 6.0 and it was fixed by forwarding the `kbn-version` header.

I have pushed 0.1.3 to npm which should fix this problem.

**Comment by justinmchase** [comment]
worked.

**Comment by mikael-lindstrom** [comment]
Great, thanks for point out this issue 👍
