### ISSUE TITLE
Provide Dockerized packaging

### ISSUE THREAD

**Issue by mohsinhijazee** [mikael-lindstrom/amazon-elasticsearch-proxy#7]
Provide a dockrized version
- Relevant tasks to build the image
- And push the image to dockerhub

Which ideally, should reduce it to just:
docker run lindstrom/aws-es-proxy your-endpoint-here

And no node installation is required.

**Comment by mikael-lindstrom** [comment]
Closing since this was fixed in https://github.com/mikael-lindstrom/amazon-elasticsearch-proxy/pull/8
